# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!
import sys
from weather import getWeather
from top_date import getDate
from clock import getTime
from  senten_load import getSentence
from PyQt5 import QtCore, QtGui, QtWidgets

import threading
class Ui_MainWindow(QtWidgets.QMainWindow):
    i = 0
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 800)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.widget_3 = QtWidgets.QWidget(self.centralWidget)
        self.widget_3.setGeometry(QtCore.QRect(0, 0, 295, 101))
        self.widget_3.setObjectName("widget_3")
        self.widget_2 = QtWidgets.QWidget(self.widget_3)
        self.widget_2.setGeometry(QtCore.QRect(20, 60, 320, 31))
        self.widget_2.setObjectName("widget_2")
        self.label_day = QtWidgets.QLabel(self.widget_2)
        self.label_day.setGeometry(QtCore.QRect(0, -12, 311, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_day.setFont(font)
        self.label_day.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_day.setObjectName("label_day")
        self.label_9 = QtWidgets.QLabel(self.widget_3)
        self.label_9.setGeometry(QtCore.QRect(0, 30, 350, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.label_18 = QtWidgets.QLabel(self.widget_3)
        self.label_18.setGeometry(QtCore.QRect(10, 10, 125, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_18.setObjectName("label_18")
        self.widget_4 = QtWidgets.QWidget(self.centralWidget)
        self.widget_4.setGeometry(QtCore.QRect(0, 110, 411, 371))
        self.widget_4.setObjectName("widget_4")
        self.label_10 = QtWidgets.QLabel(self.widget_4)
        self.label_10.setGeometry(QtCore.QRect(0, 30, 321, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_10.setObjectName("label_10")
        self.label_19 = QtWidgets.QLabel(self.widget_4)
        self.label_19.setGeometry(QtCore.QRect(10, 5, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_19.setFont(font)
        self.label_19.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_19.setObjectName("label_19")
        self.widget_5 = QtWidgets.QWidget(self.widget_4)
        self.widget_5.setGeometry(QtCore.QRect(10, 200, 400, 161))
        self.widget_5.setObjectName("widget_5")
        self.td = QtWidgets.QLabel(self.widget_5)
        self.td.setGeometry(QtCore.QRect(0, 20, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.td.setFont(font)
        self.td.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.td.setObjectName("td")
        self.dat = QtWidgets.QLabel(self.widget_5)
        self.dat.setGeometry(QtCore.QRect(0, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dat.setFont(font)
        self.dat.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.dat.setObjectName("dat")
        self.tmr = QtWidgets.QLabel(self.widget_5)
        self.tmr.setGeometry(QtCore.QRect(0, 70, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tmr.setFont(font)
        self.tmr.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.tmr.setObjectName("tmr")
        self.dat_weather = QtWidgets.QLabel(self.widget_5)
        self.dat_weather.setGeometry(QtCore.QRect(90, 120, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dat_weather.setFont(font)
        self.dat_weather.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.dat_weather.setObjectName("dat_weather")
        self.tmr_weather = QtWidgets.QLabel(self.widget_5)
        self.tmr_weather.setGeometry(QtCore.QRect(90, 70, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tmr_weather.setFont(font)
        self.tmr_weather.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.tmr_weather.setObjectName("tmr_weather")
        self.td_weather = QtWidgets.QLabel(self.widget_5)
        self.td_weather.setGeometry(QtCore.QRect(90, 20, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.td_weather.setFont(font)
        self.td_weather.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.td_weather.setObjectName("td_weather")
        self.tm_tmp = QtWidgets.QLabel(self.widget_5)
        self.tm_tmp.setGeometry(QtCore.QRect(220, 70, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tm_tmp.setFont(font)
        self.tm_tmp.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.tm_tmp.setObjectName("tm_tmp")
        self.td_tmp = QtWidgets.QLabel(self.widget_5)
        self.td_tmp.setGeometry(QtCore.QRect(220, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.td_tmp.setFont(font)
        self.td_tmp.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.td_tmp.setObjectName("td_tmp")
        self.dat_tmp = QtWidgets.QLabel(self.widget_5)
        self.dat_tmp.setGeometry(QtCore.QRect(220, 120, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dat_tmp.setFont(font)
        self.dat_tmp.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.dat_tmp.setObjectName("dat_tmp")
        self.dat_wind = QtWidgets.QLabel(self.widget_5)
        self.dat_wind.setGeometry(QtCore.QRect(340, 120, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.dat_wind.setFont(font)
        self.dat_wind.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.dat_wind.setObjectName("dat_wind")
        self.tm_wind = QtWidgets.QLabel(self.widget_5)
        self.tm_wind.setGeometry(QtCore.QRect(340, 70, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.tm_wind.setFont(font)
        self.tm_wind.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.tm_wind.setObjectName("tm_wind")
        self.td_wind = QtWidgets.QLabel(self.widget_5)
        self.td_wind.setGeometry(QtCore.QRect(340, 20, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.td_wind.setFont(font)
        self.td_wind.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.td_wind.setObjectName("td_wind")
        self.widget = QtWidgets.QWidget(self.widget_4)
        self.widget.setGeometry(QtCore.QRect(10, 60, 400, 161))
        self.widget.setObjectName("widget")
        self.td_temp = QtWidgets.QLabel(self.widget)
        self.td_temp.setGeometry(QtCore.QRect(110, 0, 180, 51))
        font = QtGui.QFont()
        font.setFamily("文泉驿点阵正黑")
        font.setPointSize(38)
        font.setBold(True)
        font.setWeight(75)
        self.td_temp.setFont(font)
        self.td_temp.setStyleSheet("color: rgb(255, 255, 255);")
        self.td_temp.setObjectName("td_temp")
        self.today_weather = QtWidgets.QLabel(self.widget)
        self.today_weather.setGeometry(QtCore.QRect(110, 60, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        self.today_weather.setFont(font)
        self.today_weather.setStyleSheet("color: rgb(255, 255, 255);\n"
"style=\"text-align:center\"")
        self.today_weather.setObjectName("today_weather")
        self.today_wind_3 = QtWidgets.QLabel(self.widget)
        self.today_wind_3.setGeometry(QtCore.QRect(200, 160, 41, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.today_wind_3.setFont(font)
        self.today_wind_3.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.today_wind_3.setObjectName("today_wind_3")
        self.today_weather_2 = QtWidgets.QLabel(self.widget)
        self.today_weather_2.setGeometry(QtCore.QRect(110, 110, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.today_weather_2.setFont(font)
        self.today_weather_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.today_weather_2.setObjectName("today_weather_2")
        self.sayhello = QtWidgets.QLabel(self.centralWidget)
        self.sayhello.setGeometry(QtCore.QRect(0, 600, 480, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        self.sayhello.setFont(font)
        self.sayhello.setStyleSheet("\n"
"color: rgb(255, 255, 255);")
        self.sayhello.setObjectName("sayhello")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 550, 25))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.widget_6 = QtWidgets.QWidget(self.centralWidget)
        self.widget_6.setGeometry(QtCore.QRect(340, 0, 201, 101))
        self.widget_6.setObjectName("widget_6")
        self.houandmin = QtWidgets.QLabel(self.widget_6)
        self.houandmin.setGeometry(QtCore.QRect(0, 40, 150, 45))
        font = QtGui.QFont()
        font.setPointSize(35)
        self.houandmin.setFont(font)
        self.houandmin.setStyleSheet("color: rgb(255, 255, 255);")
        self.houandmin.setObjectName("houandmin")
        self.second = QtWidgets.QLabel(self.widget_6)
        self.second.setGeometry(QtCore.QRect(115, 40, 31, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.second.setFont(font)
        self.second.setStyleSheet("color: rgb(255, 255, 255);")
        self.second.setObjectName("second")

        self.clock = QtWidgets.QLabel()
        self.clock.setGeometry(QtCore.QRect(320, 20, 150, 100))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.clock.setFont(font)
        self.clock.setStyleSheet("\n"
 "color: rgb(255, 255, 255);")
        self.clock.setObjectName("clock")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MagicMirror"))
        self.label_day.setText(_translate("MainWindow", "LOADING....."))
        self.label_9.setText(_translate("MainWindow", "-------------------------------------"))
        self.label_18.setText(_translate("MainWindow", "DATE TIME"))
        self.label_10.setText(_translate("MainWindow", "-----------------------------------------------------------"))
        self.label_19.setText(_translate("MainWindow", "WEATHER"))
        self.td.setText(_translate("MainWindow", "...."))
        self.dat.setText(_translate("MainWindow", "...."))
        self.tmr.setText(_translate("MainWindow", "...."))
        self.dat_weather.setText(_translate("MainWindow", "...."))
        self.tmr_weather.setText(_translate("MainWindow", "...."))
        self.td_weather.setText(_translate("MainWindow", "...."))
        self.tm_tmp.setText(_translate("MainWindow", "..°"))
        self.td_tmp.setText(_translate("MainWindow", "..°"))
        self.dat_tmp.setText(_translate("MainWindow", "..°"))
        self.dat_wind.setText(_translate("MainWindow", "........"))
        self.tm_wind.setText(_translate("MainWindow", "........"))
        self.td_wind.setText(_translate("MainWindow", "........"))
        self.td_temp.setText(_translate("MainWindow", "  ..  "))
        self.today_weather.setText(_translate("MainWindow", "......"))
        self.today_wind_3.setText(_translate("MainWindow", "风力"))
        self.today_weather_2.setText(_translate("MainWindow", "。。。/。。。"))
        self.sayhello.setText(_translate("MainWindow", "LOADING...."))
        self.houandmin.setText(_translate("MainWindow", "12:50"))
        self.second.setText(_translate("MainWindow", "35"))

    def __init__(self):
        super(Ui_MainWindow, self).__init__()
        self.setupUi(self)
        self.retranslateUi(self)
        #aligncenter
        self.today_weather.setAlignment(QtCore.Qt.AlignCenter)
        self.td_temp.setAlignment(QtCore.Qt.AlignCenter)
        self.today_weather_2.setAlignment(QtCore.Qt.AlignCenter)
        self.sayhello.setAlignment(QtCore.Qt.AlignCenter)
        self.td_weather.setAlignment(QtCore.Qt.AlignCenter)
        self.tmr_weather.setAlignment(QtCore.Qt.AlignCenter)
        self.dat_weather.setAlignment(QtCore.Qt.AlignCenter)
        #timer
        self.update_info()
        self.update_second()
        self.update_sentence()

    def update_second(self):
        _translate = QtCore.QCoreApplication.translate
        hour_time, min_time, sec_time = getTime()
        ahead_time = hour_time + ':' + min_time
        self.second.setText(_translate("MainWindow",sec_time))
        self.houandmin.setText(_translate("MainWindow",ahead_time))
        timer2 = threading.Timer(1, self.update_second)
        timer2.start()

    def update_sentence(self):
        _translate = QtCore.QCoreApplication.translate
        sent = getSentence()
        self.sayhello.setText(_translate("MainWindow", sent))
        timer3 = threading.Timer(5, self.update_sentence)
        timer3.start()

    def update_info(self):
        _translate = QtCore.QCoreApplication.translate
        # data weather
        # August 16, Wednesday
        weather_data = getWeather()
        now_tmp = "   " + weather_data[-1] + "° "
        rangeoftemp = " " + weather_data[0][4] + "°/ " + weather_data[0][3] + "°"
        self.td_temp.setText(_translate("MainWindow", now_tmp))
        self.today_weather.setText(_translate("MainWindow", weather_data[0][0]))
        self.today_weather_2.setText(_translate("MainWindow", rangeoftemp))
        self.td.setText(_translate("MainWindow", weather_data[0][1][5:19]))
        self.tmr.setText(_translate("MainWindow", weather_data[1][1][5:19]))
        self.dat.setText(_translate("MainWindow", weather_data[2][1][5:19]))

        self.td_weather.setText(_translate("MainWindow", weather_data[0][0]))
        self.td_tmp.setText(_translate("MainWindow", weather_data[0][4] + "/" + weather_data[0][3] + "°"))
        self.td_wind.setText(_translate("MainWindow", weather_data[0][2] + "%"))

        self.tmr_weather.setText(_translate("MainWindow", weather_data[1][0]))
        self.tm_tmp.setText(_translate("MainWindow", weather_data[1][4] + "/" + weather_data[1][3] + "°"))
        self.tm_wind.setText(_translate("MainWindow", weather_data[1][2] + "%"))

        self.dat_weather.setText(_translate("MainWindow", weather_data[2][0]))
        self.dat_tmp.setText(_translate("MainWindow", weather_data[2][4] + "/" + weather_data[2][3] + "°"))
        self.dat_wind.setText(_translate("MainWindow", weather_data[2][2] + "%"))

        day_information = getDate()
        self.label_day.setText(_translate("MainWindow", day_information))

        timer1 = threading.Timer(14400,self.update_info)
        timer1.start()

if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    win = Ui_MainWindow()
    win.show()
    sys.exit(app.exec_())